### ISSUE TITLE
Seekbar doesn't show on Android

### ISSUE THREAD

**Issue by clovs** [itsnubix/react-native-video-controls#22] opened 2017-04-04 11:19 UTC
Hello,

I tried your player on both device IOS&Android.
But Seekbar doesn't show on Android, working great on IOS

Maybe it's a problem with styles.sheets? don't really know..

**Comment by kylemilloy** [comment] 2017-04-05 21:26
Dupe of https://github.com/itsnubix/react-native-video-controls/issues/17

**Closed by kylemilloy** 2017-04-05 21:26 UTC
